# Generated by Django 5.1.6 on 2025-02-12 11:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geometry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometrystore',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(dim=3, srid=4326),
        ),
    ]
