# Generated by Django 5.1.6 on 2025-02-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_connection_connection_prevent_duplicate_connections'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='connection',
            name='prevent_duplicate_connections',
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.CheckConstraint(condition=models.Q(('instance_1_id__lt', models.F('instance_2_id'))), name='prevent_duplicate_connections'),
        ),
    ]
