name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: obsidian-confluence # Change this to match the id of your plugin.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x" # You might need to adjust this value to your own version

      # Get the version number and put it in an environment file
      - name: Get Version
        id: version
        run: |
          echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      # Build the plugin
      - name: Build
        id: build
        run: |
          sed -i "s/0\.0\.0/${{ env.tag }}/g" manifest.json
          npm install
          npm run build --if-present

      # Package the required files into a zip
      - name: Package
        run: |
          mkdir ${{ github.event.repository.name }}
          cp main.js manifest.json README.md ${{ github.event.repository.name }}
          zip -r ${{ github.event.repository.name }}-${{ env.tag }}.zip ${{ github.event.repository.name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.event.repository.name }}-${{ env.tag }}.zip
            main.js
            manifest.json
