on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x" # You might need to adjust this value to your own version      

      - name: Upload release assets
        if: ${{ steps.release-please.outputs.release_created }}
        run: |
          cp README.md dist/
          cp manifest.json dist/
          
          npm ci
          npm run lint -ws --if-present
          npm run prettier-check -ws --if-present
          npm run build -ws --if-present

          cd packages/obsidian
          zip -r ${{ github.event.repository.name }}-${{ env.tag }}.zip dist

          TAG=${{ steps.release-please.outputs.tag_name }}
          FILES=$(echo dist/*)
          gh release upload $TAG $FILES
          echo $FILES
          NEW_TAG="${TAG#v}"
          gh release edit $TAG -t $NEW_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}